services:
  mysql:
    build:
      context: ./db
    image: thiaguerassss/vprodb:latest
  tomcat:
    build:
      context: ./app
    image: thiaguerassss/vproapp:latest
  nginx:
    build:
      context: ./web
    image: thiaguerassss/vproweb:latest