services:
  mysql:
    build:
      context: ./db
    image: thiaguerassss/vprodb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
  memcached:
    image: memcached:1.6
    container_name: vprocache01
    ports:
      - "11211:11211"
  rabbitmq:
    image: rabbitmq:4.0
    container_name: vpromq01
    ports:
      - "5672:5672"
  tomcat:
    build:
      context: ./app
    image: thiaguerassss/vproapp
    container_name: vproapp
    ports:
      - "8080:8080"
  nginx:
    build:
      context: ./web
    image: thiaguerassss/vproweb
    container_name: vproweb
    ports:
      - "80:80"

volumes:
  vprodbdata: {}